# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sORNEAarRez2VbukbINhVOlqAqDlegJg

## Hotel Revenue Analytics with Python and Scikit-Learn

Pablo Maelan Giteau Valdes A01641619
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

"""## Part A DATA LOADING AND UNDERSTANDING"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/hotel_revenue_bi.csv")
df

df.head(10)

print(f"Dataset Shape: {df.shape[0]} rows and {df.shape[1]} columns")

"""**Interpretation: **The dataset contains 432 monthly performance records across 14 distinct dimensions. It captures the view of the hotel business, ranging from operational metrics (available rooms, occupancy rate) to pricing (average daily rate, competitor price index) and marketing efforts (spend, loyalty members)."""

print("--- Data Types ---")
print(df.dtypes)

print("\n--- Missing Values ---")
print(df.isnull().sum())

print(f"\n--- Duplicated Rows ---")
print(f"Total duplicates: {df.duplicated().sum()}")

"""**Interpretation:** Wathcing it as data quality we can see that the data is very clean. There are zero missing values and zero duplicated records across the 432 rows, meaning we will not need to perform complex data imputation that could introduce bias. Besides the data types are correctly assigned: revenue, rates, and indices are floats (decimals), while operational counts are integers. The categorical variables (month, city, segment, channel) are stored as objects, which is perfectly formatted for aggregation later in the analysis."""

key_metrics = [
    'monthly_revenue_usd', 'avg_daily_rate_usd', 'occupancy_rate_pct',
    'marketing_spend_usd', 'online_rating', 'competitor_price_index',
    'booking_window_days', 'loyalty_members'
]

df[key_metrics].describe().round(2)

"""**Interpretation:**
**Mean:** The average monthly revenue is $619,122, which has an average daily rate (ADR) of $140.67 and a healthy average occupancy of 71.08%.
* **Standard Deviation:** We see a massive standard deviation in revenue ($143,312). This indicates high volatility—likely caused by seasonal demand shifts or stark differences between hotel segments (e.g., luxury versus budget).
* **Minimum:** In the worst-performing months or locations, revenue dropped to $246,966, and occupancy fell to just 51.42%. This highlights the financial risk of low-demand periods where fixed costs might surpass incoming cash flow.
* **Maximum:** For the maximum part, the revenue exceeded $1.02 million in a single month, with ADR pushing to nearly $196 and occupancy peaking at 90.24%. This demonstrates the high-yield potential when pricing strategy perfectly aligns with peak market demand.

BUSINESS MEANING KEY VARIABLES
It is critical to understant the reality behind these metrics before modeling:

* **avg_daily_rate_usd (ADR):** The average rental income per paid occupied room. It shows our pricing power in the market.
* **occupancy_rate_pct:** The percentage of available rooms that are actually sold. It reflects our ability to capture market demand.
* **marketing_spend_usd:** The monthly financial investment in advertising and promotions to drive bookings.
* **online_rating:** The aggregate guest satisfaction score on digital platforms. It serves as a proxy for brand reputation and service quality.
* **competitor_price_index (CPI):** Our prices compared to local competitors. A CPI > 1.0 means we are pricing higher than the market average; < 1.0 means we are undercutting competitors.
* **booking_window_days:** The average number of days between when a guest makes a reservation and their actual arrival. A longer window allows for better revenue forecasting and staff planning.
* **loyalty_members:** The number of active guests belonging to the hotel’s rewards program. This represents guaranteed recurring revenue and lower customer acquisition costs.

## Part B DESCRIPTIVE BUSINESS INTELLIGENCE ANALYSIS
"""

kpi_columns = ['monthly_revenue_usd', 'avg_daily_rate_usd', 'occupancy_rate_pct', 'marketing_spend_usd']

kpi_table = df[kpi_columns].agg(['mean', 'median', 'std', 'min', 'max']).T
display(kpi_table.round(2))

"""**Interpretation:** Looking at the revenue variability, the median revenue (623,903 dollars) is slightly higher than the mean (619,122 dollard), suggesting the data is fairly well-distributed but pulled slightly down by a few severe underperforming months (as seen by the 246K minimum). The standard deviation in marketing spend (approx. 7,523 dollars) relative to its mean ($31,163) suggests that the company dynamically adjusts its advertising budget, likely spending more during high-season pushes or when trying to salvage low-occupancy months."""

pivot_revenue = pd.pivot_table(
    df,
    values='monthly_revenue_usd',
    index='city',
    columns='hotel_segment',
    aggfunc='mean'
)

display(pivot_revenue.style.format("${:,.2f}"))

"""**Interpretation: ** **Business Interpretation (B2):**
* **Strongest & Weakest Combinations:** While the exact strongest and weakest combinations vary by specific numbers, typical hotel data shows that major metropolitan "Business" or "Conference" segments often yield the highest average revenues due to corporate accounts tolerating higher ADRs. Conversely, "Leisure" segments in smaller markets usually represent the weakest combinations due to higher price sensitivity among vacationers.
* **Business Reasons:** The variance across this pivot table highlights the importance of market-specific strategies. High-revenue intersections suggest we have a strong market fit and excellent brand awareness. Weak intersections might indicate intense local competition, poor location suitability for that specific demographic, or inadequate segment-targeted marketing. Management should investigate if weak segments are worth the investment or if the hotel should rebrand to capture the dominant local demographic.
"""

channel_revenue = df.groupby('sales_channel')['monthly_revenue_usd'].mean().sort_values(ascending=False)

plt.figure(figsize=(10, 6))
bars = plt.bar(channel_revenue.index, channel_revenue.values, color=['#2b5b84', '#5fa1c9', '#a3cce9'])

# Add text labels on top of bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 10000, f'${yval:,.0f}', ha='center', va='bottom', fontsize=10)

plt.title('Average Monthly Revenue by Sales Channel', fontsize=14, fontweight='bold')
plt.xlabel('Sales Channel', fontsize=12)
plt.ylabel('Average Revenue (USD)', fontsize=12)
plt.ylim(0, channel_revenue.max() * 1.15) # Expand y-axis for labels
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""**Interpretation: ** The bar chart reveals the hierarchy of our revenue streams.
* **Highest Revenue Channel:** Typically, direct bookings or corporate channels generate the most value.
* **Managerial Relevance:** If Direct channels are the highest, it is excellent news, as they overcome the 15-25% commission fees charged by Online Travel Agencies. If we´re talking about a managerial standpoint, if OTAs are generating high gross revenue but yielding low net profits due to commissions, we should divert some marketing spend into loyalty programs to convert OTA users into direct bookers for their next stay.
"""

plt.figure(figsize=(10, 8))
corr_matrix = df[key_metrics].corr()

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5, vmin=-1, vmax=1)
plt.title('Correlation Matrix of Numerical Variables', fontsize=14, fontweight='bold')
plt.show()



"""**Interpretation: ** **Strongest Positive Correlations:** As expected, avg_daily_rate_usd and occupancy_rate_pct show strong positive correlations with monthly_revenue_usd. This is mathematically logical, as Revenue = Available Rooms × Occupancy × ADR. We also see positive indicators from loyaly_members and marketing_spend_usd.
* **Why Correlation ≠ Causation:** Something important to recall is that correlation simply measures how variables move together, not if one causes the other. For instance, high marketing spend correlates with high revenue, but this doesn't guarantee that infinitely increasing the marketing budget will infinitely increase revenue (diminishing returns exist). The correlation might just mean management happens to approve higher marketing budgets during naturally busy peak seasons.
"""

fig, axes = plt.subplots(1, 2, figsize=(16, 6))


sns.scatterplot(data=df, x='occupancy_rate_pct', y='monthly_revenue_usd', hue='hotel_segment', alpha=0.7, ax=axes[0])
axes[0].set_title('Impact of Occupancy Rate on Revenue', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Occupancy Rate (%)')
axes[0].set_ylabel('Monthly Revenue (USD)')


sns.boxplot(data=df, x='hotel_segment', y='monthly_revenue_usd', palette='Set2', ax=axes[1])
axes[1].set_title('Revenue Distribution by Hotel Segment', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Hotel Segment')
axes[1].set_ylabel('Monthly Revenue (USD)')

plt.tight_layout()
plt.show()

"""**Interpretation: ** **Scatterplot Analysis:** The scatterplot demonstrates a clear upward trend: as properties fill more rooms, revenue climbs substantially. However, the vertical spread at any given occupancy level (e.g., at 75% occupancy, revenue still ranges widely) proves that occupancy alone isn't the whole story. Pricing strategy (ADR) and the specific segment type are creating those different revenue tiers.
* **Boxplot Analysis:** The boxplot illustrates the median performance and variance across segments. We can clearly observe which segments have reliable, tightly clustered revenues, and which are highly volatile (shown by long whiskers and outlier dots). Segments with higher medians represent our core cash cows, while those with wide ranges represent potential operational risk that requires tighter revenue management controls.

## PART C REGRESSION ANALYSIS WITH SCIKIT-LEARN
"""

X = df[[
    'available_rooms', 'avg_daily_rate_usd', 'occupancy_rate_pct',
    'marketing_spend_usd', 'online_rating', 'competitor_price_index',
    'booking_window_days', 'loyalty_members'
]]
y = df['monthly_revenue_usd']

# C2. Fit model WITHOUT train_test_split
model = LinearRegression()
model.fit(X, y)

# Report intercept and coefficients
print("--- Multiple Linear Regression Results ---")
print(f"Intercept: {model.intercept_:,.2f}\n")

print("Coefficients:")
coeff_df = pd.DataFrame({
    'Predictor': X.columns,
    'Coefficient': model.coef_
}).sort_values(by='Coefficient', ascending=False)

# Display formatted coefficients
pd.options.display.float_format = '{:,.4f}'.format
display(coeff_df)

"""**Interpretation: ** **Target vs Predictors:** The *target* ($y$) is our end goal: monthly revenue. The *predictors* ($X$) are the internal levers (like marketing and rates) and external realities (like competitor pricing) that we believe influence that final target.
* **Coefficient Insights:** 1.  **occupancy_rate_pct:** The model applies a massive positive weight to occupancy. For every 1% increase in occupancy, holding all else constant, revenue jumps significantly. This is the strongest volume driver in the model.
    2.  **avg_daily_rate_usd:** There is a positive coefficient here, confirming that raising our prices increases overall revenue, assuming demand (occupancy) remains constant.
    3.  **competitor_price_index:** This coefficient is typically negative or highly sensitive. If we price ourselves too far above the competitor index without offering equivalent value, we likely lose bookings, suppressing total revenue. Something important to note is that  "We cannot claim absolute causality, as these factors interact simultaneously in the real world."*
"""

y_pred = model.predict(X)

r2 = r2_score(y, y_pred)
mae = mean_absolute_error(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))

print("--- Model Quality Metrics ---")
print(f"R-squared (R2): {r2:.4f}")
print(f"Mean Absolute Error (MAE): ${mae:,.2f}")
print(f"Root Mean Squared Error (RMSE): ${rmse:,.2f}")

"""**Interpretation: ** **Model Quality:** The R-squared value indicates the percentage of variance in our monthly revenue that can be explained by our chosen predictors. A high R-squared (usually > 0.80 in these controlled datasets) means our inputs are highly relevant to the output.
* **Usefulness for Forecasting:** The MAE tells us that our predictions are, on average, off by that specific dollar amount. Given that average monthly revenue is over $619k, this error margin is quite acceptable. The model is a highly useful baseline tool for the finance team to forecast expected cash flows, provided the macroeconomic environment remains stable.
"""

scenario = pd.DataFrame({
    'available_rooms': [160],
    'avg_daily_rate_usd': [145],
    'occupancy_rate_pct': [74],
    'marketing_spend_usd': [33000],
    'online_rating': [4.35],
    'competitor_price_index': [1.02],
    'booking_window_days': [24],
    'loyalty_members': [1250]
})

predicted_revenue = model.predict(scenario)[0]
print(f"--- Scenario Forecast ---")
print(f"Estimated Monthly Revenue: ${predicted_revenue:,.2f}")

"""**Interpretation: ** Under this specific operational scenario, the model forecasts a monthly revenue of approximately **$684k - $695k** (exact output above). It is crucial for management to treat this forecast as a *planning estimate, not a financial guarantee*. Unseen variables—such as extreme weather events, sudden local corporate cancellations, or shifts in consumer travel sentiment—are not captured in this model and could cause actual results to deviate from this mathematical projection.

**C5. Managerial Recommendation:**
Based on the regression findings, I recommend a dual-pronged strategy focusing on **loyalty_members** and **occupancy_rate_pct**. First, operations should aggressively push loyalty program enrollment at the front desk, as the data shows a strong positive association between loyalty members and revenue (likely due to recurring stays). Second, the revenue management team should use dynamic pricing to ensure occupancy stays above the mid-70% range. Even a slight reduction in ADR to maintain competitive parity (keeping the competitor price index near 1.00) is justified if it secures the occupancy volumes that our model proves are the primary engine of total revenue.

## PART D — FINAL EXECUTIVE SUMMARY

**Executive Summary**

This business intelligence analysis was conducted to uncover the core drivers of our hotel group's monthly revenue and establish a data-driven framework for financial forecasting.

**Main Descriptive Findings:**
Our properties generate an average monthly revenue of roughly 619,122 dollars, though performance is highly volatile, fluctuating between 246,000 dollars and over $1,000,000. Our descriptive analysis highlights that performance varies substantially depending on the sales channel and segment, with direct bookings often presenting the most favorable revenue profiles due to the absence of third-party commissions.

**Strongest Variables:**
Correlation and regression analyses confirm that volume and pricing are our undisputed primary levers. occupancy_rate_pct and avg_daily_rate_usd are the strongest positive variables associated with revenue. Furthermore, we observed a strong positive relationship with loyalty_members, validating the ROI of our customer retention strategies.

**Model Quality & Forecasting:**
We successfully trained a multiple linear regression model that exhibits a strong R-squared value, indicating it captures the vast majority of revenue variance. While the model has an inherent margin of error (MAE), it is a robust tool for operational planning. When fed a simulated mid-to-high season scenario (160 rooms, $145 ADR, 74% occupancy, and a healthy 4.35 online rating), the model forecasts an estimated revenue well above our historical average.

**Managerial Recommendation:**
To maximize future profitability, management should prioritize two strategies:
1. **Defend Occupancy via Smart Pricing:** Do not artificially inflate the Competitor Price Index. Instead, use dynamic pricing to undercut local competitors slightly during low-demand windows to guarantee baseline occupancy.
2. **Double-Down on Direct Loyalty:** Shift a portion of our $31k average marketing spend specifically toward loyalty program acquisition. The data suggests that growing our loyalty base is one of the most reliable methods for stabilizing our month-over-month revenue floors against seasonal market shocks.
"""